version: "3.7"

services:
  svnadmin:
    image: ${SVN_IMAGE:-registry.cn-hangzhou.aliyuncs.com/witersencom/svnadmin:2.5.10}
    container_name: svnadmin
    restart: unless-stopped
    expose:
      - "80"
      - "3690"
    volumes:
      - ${SVN_DATA_PATH:-/data/svn}/svnadmin:/home/svnadmin:Z
      - ${SVN_DATA_PATH:-/data/svn}/conf.d:/etc/httpd/conf.d:Z
      - ${SVN_DATA_PATH:-/data/svn}/sasl2:/etc/sasl2:Z
      - ./apache-servername.conf:/etc/httpd/conf.d/00-servername.conf:ro,Z
    environment:
      - APACHE_SERVER_NAME=${DOMAIN:-svn.lab.icinfra.ltd}

  nginx:
    image: nginx:alpine
    container_name: svn-nginx-proxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "3690:3690"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
      - ./ssl:/etc/nginx/ssl:ro,Z
    depends_on:
      - svnadmin
    command: nginx -g 'daemon off;'
