version: "3.7"

services:
  # SVN Admin 服务
  svnadmin:
    image: registry.cn-hangzhou.aliyuncs.com/witersencom/svnadmin:2.5.10
    container_name: svnadmin
    restart: unless-stopped
    # 只暴露内部端口，不直接对外
    expose:
      - "80"
      - "3690"
    volumes:
      # CentOS 7.9 SELinux兼容的挂载方式
      - /data/svn/svnadmin:/home/svnadmin:Z
      - /data/svn/conf.d:/etc/httpd/conf.d:Z
      - /data/svn/sasl2:/etc/sasl2:Z
    networks:
      - svn-network
    # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx HTTPS 代理
  nginx:
    image: nginx:alpine
    container_name: svn-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3690:3690"  # SVN协议端口直接透传
    volumes:
      # Nginx 配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL 证书目录
      - ./ssl:/etc/nginx/ssl:ro
      # 日志目录
      - ./logs:/var/log/nginx
    depends_on:
      - svnadmin
    networks:
      - svn-network
    # 添加健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  svn-network:
    driver: bridge
